//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDbDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDbUser
    {
        public RDbUser()
        {
            this.UpcLogs = new HashSet<UpcLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Collections { get; set; }
    
        public virtual ICollection<UpcLog> UpcLogs { get; set; }
    }
}
